### ISSUE TITLE
How can I remove this repo?

### ISSUE THREAD

**Issue by abinashdash17** [xeffyr/termux-x-repository#10]
An option to remove the repo in the `enablerepo.sh` would be appreciated. Not an issue actually.

**Comment by xeffyr** [comment]
Ok, I can add script 'removerepo.sh' which will remove repository. But currently you can edit your `sources.list`  file by removing lines containing `https://xeffyr.github.io/termux-x-repository/`.

Or you can try this command:
```
sed -i '/https:\/\/xeffyr.github.io\/termux-x-repository/d' "${PREFIX}/etc/apt/sources.list"
```

**Comment by abinashdash17** [comment]
I've already edited `sources.list` to remove repo(just like in ubuntu). The `removerepo.sh` would be an easier way actually so that one doesn't have to edit the source list manually.

**Comment by xeffyr** [comment]
Fixed now.
