### ISSUE TITLE
A VNC server is already running as :1

### ISSUE THREAD

**Issue by CG-man** [xeffyr/termux-x-repository#16]
startx

Warning: localhost:1 is taken because of /data/data/com.termux/files/usr/tmp/.X11-unix/X1
Remove this file if there is no X server localhost:1
A VNC server is already running as :1

**Comment by xeffyr** [comment]
Looks like that you don't stop VNC server gracefully.

Run these commands:
```
rm -f /data/data/com.termux/files/usr/tmp/.X11-unix/X1
rm -f /data/data/com.termux/files/usr/tmp/.X1-lock
```

Next time do ```vncserver -kill :1``` or ctrl-c if startx running in foreground.
