### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by T4P4N** [xeffyr/termux-x-repository#17]
![screenshot_2018-04-25-16-13-00-132_com realvnc viewer android](https://user-images.githubusercontent.com/32695903/39241451-93ba5706-48a4-11e8-94bf-03869580a148.png)

**Comment by T4P4N** [comment]
only date & time is Showing!

**Comment by xeffyr** [comment]
Which OS ? There is an 'unsolvable' problems on Android 8.
