### ISSUE TITLE
Openbox crashes because it can't find libXcursor.so.1

### ISSUE THREAD

**Issue by omrisim210** [xeffyr/termux-x-repository#4]
I added this repo and installed `termux-desktop`, but after running `startx` it crashed. I commented out the part that redirects output from openbox to `/dev/null` and now when I run `startx` I get this:

```
New 'Termux Desktop' desktop is localhost:1

Log file is /data/data/com.termux/files/home/.vnc/localhost:1.log

CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/openbox": library "libXcursor.so.1" not found
/data/data/com.termux/files/usr/bin/startx: line 39: 28172 Aborted                 openbox-session
Killing Xvnc process ID 28167
```
First of all I tried doing `pkg s xcursor` and it was already installed. I tried symlinking `$PREFIX/lib/libXcursor.so` to `$PREFIX/lib/libXcursor.so.1` and for some reason it didn't work. What did work was copying `$PREFIX/lib/libXcursor.so` to `$PREFIX/lib/libXcursor.so.1`. After that openbox launched fine but `env` complained about python not being installed so I installed it, and then python complained about PyXDG not being installed so I installed it through `pip`, and now finally everything is running fine

So perhaps the libXcursor package needs to be adjusted? I'd do it if I knew how to

**Comment by xeffyr** [comment]
Problem with libxcursor is fixed.
Normal apps will be available when gtk (both 2 & 3 versions) will be added for all architectures.
