### ISSUE TITLE
Add application to dosbox 

### ISSUE THREAD

**Issue by lofcz** [xeffyr/termux-x-repository#5]
Hey,
just curious, how can one add apps to dosbox provided with this repo? Or any apps in general to openbox. Just a quick guide would be a lifesaver.
I'm trying to boot original doom from dosbox now. 
Thanks

**Comment by xeffyr** [comment]
Currently, openbox menu editing available only via `${PREFIX}/etc/xdg/openbox/menu.xml`.

**Comment by lofcz** [comment]
Thanks, that should help me out. 
Guess this can be closed now.
