### ISSUE TITLE
Question: Minimal installation?

### ISSUE THREAD

**Issue by Neo-Oli** [xeffyr/termux-x-repository#6]
Basically at the moment I only need feh and xterm and don't want to install DosBox or that Powder Game. What packages do need to install to get only a minimal base system?

**Comment by hanu-man** [comment]
when i give command startx and after go and setup vncviewer it shows black screen
what to do now

**Comment by xeffyr** [comment]
@Neo-Oli, it is possible to install xterm & feh without openbox and other stuff.
Just do:
```
apt install feh xterm
```
If VNC server needed, then `apt install tigervnc`.

**Comment by Neo-Oli** [comment]
Ah, I got it working. I just needed to download the startx script manually from your repository.

**Comment by xeffyr** [comment]
You don't need script 'startx' unless you want an Openbox environment. Install package tigervnc and run `vncserver` instead.
